---

- hosts: '{{ target }}'
  remote_user: '{{ user }}'
  become: yes
  become_method: su
  become_user: root
  tasks:
  - name: Change Name of Machine
    hostname:
      name: '{{ namehost }}'
  - name: Update system
    dnf:
      name: "*"
      state: latest
  - name: Install requeriments of disable selinux
    become: yes
    dnf:
      name: "libselinux-python"
      state: latest
  - name: Disable SeLinux
    become: yes
    selinux:
      state: disabled
  - name: Stoping FirewallD
    become: yes
    systemd:
      name: firewalld
      state: stopped
