---

- hosts: '{{ target }}'
  remote_user: '{{ user }}'
  become: yes
  become_method: su
  become_user: root
  tasks:
# añadir trozo de código que exporta el path en /etc/profile. Debe añadirse justo antes de la línea de código que hace el export largo: export PATH USER LOGNAME MAIL HOSTNAME HISTSIZE HISTCONTROL. 

#if [ -z $JAVA_HOME ];then
#    export JAVA_HOME="/usr/java/latest/jre"
#    export PATH=$JAVA_HOME/bin:$PATH
#fi
